version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install awscli
      - cd project-1

  build:
    commands:
      - echo Packaging Lambda function...
      - pip install -r requirements.txt -t package/
      - cp -r src/* package/
      - cd package
      - zip -r9 ../lambda_function.zip .

  post_build:
    commands:
      - echo Uploading lambda_function.zip to S3...
      - aws s3 cp ../lambda_function.zip s3://lambda-code-dawid-otomotoscraper/project-1/lambda_function.zip
      - echo Deploying Lambda function...
      - aws lambda update-function-code --function-name CarPriceScraper --s3-bucket lambda-code-dawid-otomotoscraper --s3-key project-1/lambda_function.zip
      - echo "Lambda function updated successfully"
