version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install awscli

  build:
    commands:
      - echo Packaging Lambda function...
      - pip install -r requirements.txt -t package/
      - cp -r src/* package/
      - cp appspec.yml package/  # Ensure appspec.yml is included
      - cd package
      - zip -r9 ../lambda_function.zip .

artifacts:
  files:
    - lambda_function.zip
  discard-paths: yes
